# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-06 13:19
from __future__ import unicode_literals

import contracts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_contract__normalized_labor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='current_price',
            field=contracts.models.CashField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hourly_rate_year1',
            field=contracts.models.CashField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hourly_rate_year2',
            field=contracts.models.CashField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hourly_rate_year3',
            field=contracts.models.CashField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hourly_rate_year4',
            field=contracts.models.CashField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hourly_rate_year5',
            field=contracts.models.CashField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='next_year_price',
            field=contracts.models.CashField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='second_year_price',
            field=contracts.models.CashField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
