# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-08 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_auto_20170306_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='idv_piid',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='contract',
            name='vendor_name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
