# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_idv_piid_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='piid',
        ),
    ]
