# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-06 13:19
from __future__ import unicode_literals

import contracts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0015_auto_20170131_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedpricelistrow',
            name='base_year_rate',
            field=contracts.models.CashField(decimal_places=2, max_digits=10),
        ),
    ]
