# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-16 16:54
from __future__ import unicode_literals

import data_capture.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_capture', '0016_auto_20170306_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptedPriceListSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_file_name', models.CharField(blank=True, max_length=128)),
                ('uploaded_file_content_type', models.CharField(blank=True, max_length=128)),
                ('valid_row_count', models.IntegerField(blank=True, null=True)),
                ('invalid_row_count', models.IntegerField(blank=True, null=True)),
                ('session_state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HashedUploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hex_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('contents', models.FileField(storage=data_capture.models.SlowpokeStorage(), upload_to='data_capture_uploaded_files/')),
            ],
        ),
        migrations.CreateModel(
            name='SlowpokeStorageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('size', models.IntegerField()),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='attemptedpricelistsubmission',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_capture.HashedUploadedFile'),
        ),
    ]
